from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')

start=s.index('async function searchCompanies()')
end=s.index('function addProspect(i)',start)
new='''async function getValidationCompanies(){try{let r=await fetch("./data/receita_pa.json?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("Base local ainda não gerada");return await r.json()}catch(e){return []}}\nfunction filterValidationCompanies(rows){let uf=($("fUf").value||"").trim().toUpperCase(),city=($("fCity").value||"").trim().toLowerCase(),cnae=dig($("fCnae").value),days=+$("fDays").value,size=$("fSize").value,sim=bool($("fSimples").value),mei=bool($("fMei").value),limit=+$("fLimit").value,cutoff=Date.now()-days*86400000;return rows.filter(x=>{if(uf&&String(x.uf||"").toUpperCase()!=uf)return false;if(city&&!String(x.municipio||"").toLowerCase().includes(city))return false;if(cnae&&!String(x.cnae_principal||"").replace(/\\D/g,"").startsWith(cnae))return false;if(size&&String(x.porte||"").toUpperCase()!=size.toUpperCase())return false;if(sim!==null&&x.simples!==null&&Boolean(x.simples)!==sim)return false;if(mei!==null&&x.mei!==null&&Boolean(x.mei)!==mei)return false;if(x.data_abertura&&new Date(x.data_abertura).getTime()<cutoff)return false;return true}).slice(0,limit)}\nasync function searchCompanies(){$("searchResults").innerHTML='<div class="empty">Pesquisando...</div>';let data=null,error=null;try{let r=await sb.rpc("buscar_empresas_receita",{p_uf:$("fUf").value||null,p_municipio:$("fCity").value||null,p_cnae:dig($("fCnae").value)||null,p_dias:+$("fDays").value,p_porte:$("fSize").value||null,p_simples:bool($("fSimples").value),p_mei:bool($("fMei").value),p_limite:+$("fLimit").value});data=r.data;error=r.error}catch(e){error=e}if(error||!data?.length){let local=await getValidationCompanies();data=filterValidationCompanies(local)}$("resultCount").textContent=(data?.length||0)+" empresas";if(!data?.length)return $("searchResults").innerHTML='<div class="empty">Nenhuma empresa encontrada na base de validação.</div>';$("searchResults").innerHTML='<table><thead><tr><th>CNPJ</th><th>Razão Social</th><th>Abertura</th><th>Município/UF</th><th>CNAE</th><th>Porte</th><th>Contato</th><th>Score</th><th>Ações</th></tr></thead><tbody>'+data.map((x,i)=>{let sc=prospectScore(x);return `<tr><td>${esc(formatCnpj(x.cnpj))}</td><td><b>${esc(x.razao_social)}</b></td><td>${esc(x.data_abertura)}</td><td>${esc(x.municipio)}/${esc(x.uf)}</td><td>${esc(x.cnae_principal)}</td><td>${esc(x.porte||"-")}</td><td>${esc(x.telefone||x.email||"-")}</td><td><span class="pill">${sc}</span></td><td><div class="rowactions"><button class="action" onclick="previewCompany(${i})">Detalhes</button><button class="action primary" onclick="addProspect(${i})">Prospect</button></div></td></tr>`}).join("")+'</tbody></table>';window.lastSearch=data}\n'''
s=s[:start]+new+s[end:]

start=s.index('async function refreshRfbStatus()')
end=s.index('(async()=>{',start)
new2='''async function refreshRfbStatus(){try{let data=null;try{let r=await sb.from("receita_import_status").select("referencia,status,concluido_em,registros,proxima_verificacao,erro").order("id",{ascending:false}).limit(1).maybeSingle();if(!r.error)data=r.data}catch(e){}if(!data){try{let r=await fetch("./data/status.json?ts="+Date.now(),{cache:"no-store"});if(r.ok)data=await r.json()}catch(e){}}if(!data)return;let label=data.status==="concluido"?"Base de validação pronta":data.status==="processando"?"Atualizando base...":"Falha na atualização";let extra=data.status==="concluido"?` • competência ${data.referencia} • ${Number(data.registros||0).toLocaleString("pt-BR")} registros`:"";document.querySelectorAll("[data-rfb-status]").forEach(el=>{el.textContent=label+extra;el.className="status "+(data.status==="concluido"?"on":data.status==="processando"?"warn":"off")})}catch(e){console.warn("Status RFB",e)}}\n'''
s=s[:start]+new2+s[end:]
p.write_text(s,encoding='utf-8')
print('index.html preparado para fallback local')
